
django.utils.autoreload INFO 2025-03-22 18:21:49,175 autoreload 95573 139836997738624 Watching for file changes with StatReloader
django.utils.autoreload INFO 2025-03-22 18:26:51,575 autoreload 97443 140639524647040 Watching for file changes with StatReloader
django.utils.autoreload INFO 2025-03-22 18:38:40,980 autoreload 101030 140322500759680 Watching for file changes with StatReloader
django.security.DisallowedHost ERROR 2025-03-22 18:38:44,291 exception 101030 140322450437824 Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/finn/Group-Engineering-Project/.venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/finn/Group-Engineering-Project/.venv/lib/python3.12/site-packages/django/utils/deprecation.py", line 128, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/finn/Group-Engineering-Project/.venv/lib/python3.12/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "/home/finn/Group-Engineering-Project/.venv/lib/python3.12/site-packages/django/http/request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
django.request WARNING 2025-03-22 18:38:44,307 log 101030 140322450437824 Bad Request: /home/accounts/login/
django.server WARNING 2025-03-22 18:38:44,307 basehttp 101030 140322450437824 "GET /home/accounts/login/ HTTP/1.1" 400 75229
django.security.DisallowedHost ERROR 2025-03-22 18:38:44,390 exception 101030 140322450437824 Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/finn/Group-Engineering-Project/.venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/finn/Group-Engineering-Project/.venv/lib/python3.12/site-packages/django/utils/deprecation.py", line 128, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/finn/Group-Engineering-Project/.venv/lib/python3.12/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "/home/finn/Group-Engineering-Project/.venv/lib/python3.12/site-packages/django/http/request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
django.request WARNING 2025-03-22 18:38:44,399 log 101030 140322450437824 Bad Request: /favicon.ico
django.server WARNING 2025-03-22 18:38:44,399 basehttp 101030 140322450437824 "GET /favicon.ico HTTP/1.1" 400 74760
django.security.DisallowedHost ERROR 2025-03-22 18:38:45,315 exception 101030 140322450437824 Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/finn/Group-Engineering-Project/.venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/finn/Group-Engineering-Project/.venv/lib/python3.12/site-packages/django/utils/deprecation.py", line 128, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/finn/Group-Engineering-Project/.venv/lib/python3.12/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "/home/finn/Group-Engineering-Project/.venv/lib/python3.12/site-packages/django/http/request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
django.request WARNING 2025-03-22 18:38:45,323 log 101030 140322450437824 Bad Request: /home/accounts/login/
django.server WARNING 2025-03-22 18:38:45,324 basehttp 101030 140322450437824 "GET /home/accounts/login/ HTTP/1.1" 400 75229
django.utils.autoreload INFO 2025-03-22 18:39:03,940 autoreload 101030 140322500759680 /home/finn/Group-Engineering-Project/SustainableApplication/SustainableApplication/settings.py changed, reloading.
django.utils.autoreload INFO 2025-03-22 18:39:04,116 autoreload 101211 140545121677440 Watching for file changes with StatReloader
django.server INFO 2025-03-22 18:39:05,765 basehttp 101211 140545071511232 "GET /home/accounts/login/ HTTP/1.1" 200 7747
django.server INFO 2025-03-22 18:39:05,820 basehttp 101211 140545071511232 "GET /static/auth.css HTTP/1.1" 200 1844
